services:
  mongo:
    image: mongo:6.0
    container_name: banzai-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: banzai-todo-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - MONGODB_DATABASE=banzai
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - mongo

volumes:
  mongo_data:
